### ISSUE TITLE
Seeking support. Is it possible to add mods to the Forest without the modapi.exe?

### ISSUE THREAD

**Issue by dmaahs2017** [tommojphillips/ModAPI#3]
I am running the forest via steam proton for Linux. I tried to use WINE to run the modapi.exe in order to install some mods. (Downloaded from [https://modapi.survivetheforest.net/](https://modapi.survivetheforest.net/).

Anyways, I was wondering if there is a way to install the mods onto the Forest without using the modapi.exe? If so some help would be appreciated, It's a very niche thing, and I've not found much info around this online.

My hope is that I can just move some files somewhere into the forest install directory

**Comment by tommojphillips** [comment]
this is mod api for my summer car bro
